### PR TITLE
#12: add payment info

### PR DESCRIPTION
**Pull request by hinchley2018**
https://github.com/stripe/stripe-js
https://stripe.com/docs/js/initializing

### CODE REVIEW

**Comment by hinchley2018** [comment]
OUR DEVELOPERS NEED THIS NOW!!!

**Comment by hinchley2018** [comment]
WHY IS IT TAKING SO LONG TO REVIEW MY PULL REQUEST!!!!??? 
😠 😠

**Comment by hinchley2018** [comment]
LITERLALLY I DONT ENVIN GET WHY WE DO PULL REQUESTS I COULD JUST MERGE IT MYSELF!!!
😡 😡 👎

**Comment by CodeSTACKE** [comment]
Accept my pull request, why so late

**Comment by hinchley2018** [comment]
My code is the best, doesn't even need tests, just MERGE IT ALREADY!!!

**Comment by TylerGoldsmith** [comment]
Johnathon
The links are good but it would help me if you would give a description to know what I was initially looking at.
We will review this with the utmost urgency.

Jyoti
We are reviewing the code now.

**Comment by hinchley2018** [comment]
Done showing off bad pr

**Pull request closed without merging**
